# 博客信息
blog:
  title: brite's Blog
  description: 探索学习 Python 的数据分析师，包括 Python教程、学习路径、常用工具、 VSCode 配置及数据分析等领域的相关知识。
  url: https://geoqiao.github.io/contents/
  content_dir: "./contents/"
  blog_dir: "blog/"
  rss_atom_path: "atom.xml"
  author:
    name: brite
    email: geoqiao@example.com

# GitHub 相关配置
github:
  name: briteming # GitHub用户名
  repo: briteming/ggb # GitHub仓库名

# Google Search Console
GoogleSearchConsole:
  content: DRggZlykSzc8M9TyaS0BPSRE7Kvw8W9hHt5pZrIMm3Y # Google Search Console ID
  verify: true # 是否验证

theme:
  path: "templates/default_theme"
